server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/saas_db
    username: your_username
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: your_jwt_secret
  expiration: 3600000
